# Generated by Django 3.1.4 on 2022-03-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='company_id',
        ),
    ]
