# Generated by Django 3.1.4 on 2022-03-17 09:35

from django.db import migrations, models
import django.db.models.deletion
import items.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.company_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, db_column='name_en', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, db_column='description_en', null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('ingredients_en', models.TextField(blank=True, db_column='ingredients_en', null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('usage_en', models.TextField(blank=True, db_column='usage_en', null=True)),
                ('caution', models.TextField(blank=True, null=True)),
                ('caution_en', models.TextField(blank=True, db_column='caution_en', null=True)),
                ('storage', models.TextField(blank=True, null=True)),
                ('storage_en', models.TextField(blank=True, db_column='storage_en', null=True)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('video', models.CharField(blank=True, max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=items.models.item_directory_path)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=items.models.poster_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='items.Category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.company')),
                ('subcategories', models.ManyToManyField(blank=True, null=True, to='items.SubCategory')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='items.Tag')),
                ('types', models.ManyToManyField(blank=True, null=True, to='items.Type')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.type'),
        ),
    ]
