# Generated by Django 3.1.4 on 2022-03-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='name',
        ),
    ]
