# Generated by Django 3.1.4 on 2022-03-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
