# Generated by Django 3.1.4 on 2022-03-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='types',
        ),
        migrations.RemoveField(
            model_name='item',
            name='video',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
